version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: financial_pipeline_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - ALLOWED_HOSTS=localhost, 127.0.0.1,financial_pipeline_app
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=sam
      - DB_PASSWORD=samuel
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  db:
    image: postgres:15
    container_name: financial_pipeline_db
    environment:
      POSTGRES_USER: sam
      POSTGRES_PASSWORD: samuel
      POSTGRES_DB: crypto_db_new
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: financial_pipeline_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
