version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: financial_pipeline_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      - ALLOWED_HOSTS=localhost, 127.0.0.1,financial_pipeline_app
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=sam
      - DB_PASSWORD=samuel
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  db:
    image: postgres:15
    container_name: financial_pipeline_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: financial_pipeline_redis
    ports:
      - "6379:6379"
  
  # Dedicated service that runs the crypto data fectch scheduled job
  cron_scheduler:
    image: ${IMAGE_NAME:-financial_pipeline_app}:latest # Use the image built by Django service
    depends_on:
      - financial_pipeline_app        # Ensure the main app (and thus the DB) is running
      - db
    restart: "unless-stopped"
    volumes:
      # Mount the crontab config file
      - ./crontab/crons.conf:/etc/crontabs/root:ro
    
    env_file:
      - .env
    command: /usr/sbin/crond -f -l 8

volumes:
  postgres_data:
